name: AthenaGM
main: io.github.redwallhp.athenagm.AthenaGM
description: Athena Game Manager
author: redwall_hp
version: ${version}
load: startup


permissions:
  athenagm.admin:
    description: Admin functions
    children:
      athenagm.moderator: true
  athenagm.moderator:
    description: Moderation functions
  athenagm.player:
    description: General functions
    default: true


commands:
  athena:
    usage: /athena <subcommand>
    description: Admin commands
    permission: athenagm.admin
    permission-message: You don't have permission to do that.
  hub:
    usage: /hub
    description: Return to the minigames hub
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  arenas:
    usage: /arenas
    description: List arenas
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  join:
    usage: /join <arena id>
    description: Join an arena
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  teams:
    usage: /teams
    description: List the teams available in a match
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  team:
    usage: /team <team id>
    description: Join a team in the current match
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  autojoin:
    usage: /autojoin
    description: Automatically join a team
    permission: athenagm.player
    permission-message: You don't have permission to do that.
    aliases: [aj]
  spectate:
    usage: /spectate
    description: Switch to the Spectator team
    permission: athenagm.player
    permission-message: You don't have permission to do that.
    aliases: [spec]
  score:
    usage: /score
    description: Show your own score
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  timeleft:
    usage: "/timeleft [arena]"
    description: The time left in a match. Optionally specify another arena.
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  players:
    usage: /players
    description: Show the players in the current match, ranked by score.
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  tmsg:
    aliases: [t]
    usage: /tmsg <msg>
    description: Send a message to your team
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  region:
    usage: /region <subcommand>
    aliases: [rg]
    description: Region management commands
    permission: athenagm.admin
    permission-message: You don't have permission to do that.
  votemap:
    usage: /votemap [map name]
    description: Start a map vote. Omit the map name to get a list of valid options.
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  votenext:
    usage: /votenext
    description: Start a vote for the next map. Three random options will be selected.
    permission: athenagm.player
    permission-message: You don't have permission to do that.
  vote:
    usage: /vote <choice>
    description: Cast your ballot in an ongoing vote.
    permission: athenagm.player
    permission-message: You don't have permission to do that.
