name: Deploy
on: [ push ]
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Gradle Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - name: Deploy to zav-1
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: na889.pebblehost.com
          server-dir: plugins/
          local-dir: build/libs/
          username: ${{ secrets.zav_username }}
          password: ${{ secrets.password }}

      - name: Deploy to contagion-1
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: na889.pebblehost.com
          server-dir: plugins/
          local-dir: build/libs/
          username: ${{ secrets.contagion_username }}
          password: ${{ secrets.password }}

      - name: Deploy to tu-1
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: na648.pebblehost.com
          server-dir: plugins/
          local-dir: build/libs/
          username: ${{ secrets.tu_username }}
          password: ${{ secrets.password }}
